const {
  COCOSCAN_DISCORD_WEBHOOK_URL,
  GEMINI_API_KEY,
  YOUTUBE_API_KEY,
  GOOGLE_SEARCH_API_KEY,
  GOOGLE_SEARCH_ENGINE_ID,
} = process.env;

export {
  COCOSCAN_DISCORD_WEBHOOK_URL,
  GEMINI_API_KEY,
  YOUTUBE_API_KEY,
  GOOGLE_SEARCH_API_KEY,
  GOOGLE_SEARCH_ENGINE_ID,
};
